import React from "react";
import Head from "next/head";

const NavigationBar = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>NavigationBar</nav>
    </>
  );
};

export default NavigationBar;
